## ------------------------------------------------------------------------- ##
## Directory Structure
## ------------------------------------------------------------------------- ##
# All paths are relative to config-root (.emacs.d/) if they are not absolute
## .emacs.d/					--> config-root
##   init.el
##	 config/
##	   core/
##     modes/
##     custom.el
##	 modules/
##     elpa/
##     user/
##	 temp/
##     backup/
##	   autosave/

config-paths:
  # Default path of buffer
  default:              "~/"

  # Core configuration files
  core:                 "config/core"
  # Mode specific configurations
  mode:                 "config/modes"
  # Emacs custom file (typically unused)
  custom-file:          "config/custom.el"

  # Archived packages from ELPA/MELPA
  elpa-modules:         "modules/elpa"
  # User packages that are manually installed or created
  user-modules:         "modules/user"

  # Temporary settings
  temp:                 "temp"
  backup:               "temp/backup"
  autosave:             "temp/autosave"

  # Snippets
  tempel:               "etc/snippets/tempel.snippets"

## ------------------------------------------------------------------------- ##
## User Info
## ------------------------------------------------------------------------- ##
user-info:
  full-name:            "John P. Hilbert"
  mail-address:         "jphilbert@gmail.com"

## ------------------------------------------------------------------------- ##
## Specific Application Paths / Settings
## ------------------------------------------------------------------------- ##
applications:
  spell:
    exe:                "C:/bin/hunspell/bin/hunspell.exe"
    dict:               "C:/bin/hunspell/share/hunspell/en_US.aff"
  ripgrep:
    exe:                "C:/bin/ripgrep/rg.exe"
  r:
    exe:                "rterm.exe"
  python:
    exe:                "ipython"
    args:               "-i --simple-prompt --InteractiveShell.display_page=True --TerminalInteractiveShell.prompts_class=IPython.terminal.prompts.ClassicPrompts"
  zip7:
    exe:                ""
  git:
    exe:                ""
  pandoc:
    exe:                ""

  sql:
    exe:
      oracle:           sqlplus
      ms:               ~/apps/sqlcmdline.bat
    query-directory:    etc/sql

    servers:
      name:
        product:        ""
        uid:            ""
        pw:             ""
