-- TODO
-- SELECT
--   TYPE,
--   SUBSTR(owner || '.' || NAME, 1, 70) AS NAME
-- FROM
--   all_users
-- WHERE
--   owner LIKE '%OWNER_PATTERN%'
--     AND
--   NAME LIKE '%TABLE_PATTERN%'
-- ORDER BY
--   TYPE,
--   owner,
--   NAME
