SELECT
  LEFT(COLUMN_NAME, 40) AS col_name,
  LEFT(DATA_TYPE, 20) AS date_type,
  CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR(6)) AS LENGTH,
  is_nullable
FROM
  INFORMATION_SCHEMA.COLUMNS
WHERE
  (TABLE_schema + '.' + TABLE_NAME) = '${schema-table}'
