SELECT
  top 100
  concat(LEFT(TABLE_SCHEMA, 20), '.',
         LEFT(TABLE_NAME, 45)) TABLE_NAME,
  LEFT(TABLE_TYPE, 10) TABLE_TYPE
FROM
  INFORMATION_SCHEMA.TABLES
WHERE
  TABLE_SCHEMA LIKE '${schema}'
    AND
  TABLE_NAME LIKE '${table}'
ORDER BY 1
