SELECT TOP 100
  LEFT(TABLE_TYPE, 10) AS TYPE,
  CONCAT(LEFT(TABLE_SCHEMA, 14), '.',
    LEFT(TABLE_NAME, 34)) AS TABLE_NAME
FROM
  INFORMATION_SCHEMA.TABLES
WHERE
  TABLE_SCHEMA LIKE '${schema}'
    AND
  TABLE_NAME LIKE '${table}'
ORDER BY
  2, 1
