SELECT
  top 100
  concat(LEFT(TABLE_SCHEMA, 20), '.',
         LEFT(TABLE_NAME, 45)) TABLE_NAME,
  LEFT(COLUMN_NAME, 30) COLUMN_NAME
FROM
  INFORMATION_SCHEMA.COLUMNS
WHERE
  COLUMN_NAME LIKE '${column}'
    AND
  TABLE_NAME LIKE '${table}'
ORDER BY
  TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME
