SELECT TOP 100
  CONCAT(LEFT(TABLE_SCHEMA, 14), '.',
    LEFT(TABLE_NAME, 34)) AS TABLE_NAME,
  LEFT(COLUMN_NAME, 28) AS COLUMN_NAME
FROM
  INFORMATION_SCHEMA.COLUMNS
WHERE
  COLUMN_NAME LIKE '${column}'
    AND
  TABLE_NAME LIKE '${table}'
ORDER BY
  TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME
